.gitignore
labvm/readme.md
labvm/services/atdServiceUpdater/atdServiceUpdater.py
labvm/services/atdServiceUpdater/atdServiceUpdater.service
labvm/services/atd_docs/atd_docs.service
labvm/services/atd_docs/atd_docs.sh
labvm/services/readme.md
labvm/services/serviceUpdater.yml

Brings in 2 service files, atdServiceUpdater (used to add or update service on the labvm), and atd_docs (used to pull recent labguides onto the labvm.

Rob service updater

---

labvm/services/gitConfigletSync/gitConfigletSync.py
labvm/services/gitConfigletSync/gitConfigletSync.service
labvm/services/serviceUpdater.yml

PR to add gitConfigletSync service into atd-public.  Will wait to merge this PR once the service has been merged into the atd repo.

Adding gitConfigletSync

---

labvm/services/gitConfigletSync/gitConfigletSync.py

Updated GitConfigletSync to latest from main repo

Updated GitConfiglet to Latest

---

topologies/all/login.py
topologies/datacenter/files/MenuOptions.yaml
topologies/routing/files/MenuOptions.yaml

Fixed issue where user couldn't get back to login.py script after entering bash.  Also added `reset` option to menu.

Added reset and fixed bash bug

---

topologies/routing/configlets/AAA
topologies/routing/files/cvp/cvp_info.yaml

**All modifications under /topologies/routing**
- Adding cvp_info.yml to /topologies/routing/files/cvp/

Add cvp_info.yml to RATD

---

topologies/routing/files/.screenrc

only modifications under /topologies/routing
created screenrc file for RATD under topologies/routing/files

Create RATD screenrc

---

topologies/routing/files/MenuOptions.yaml

**All modifications performed in /topologies/routing directory**
Adding MenuOptions.yaml file to /topologies/routing/files/

Create RATD MenuOptions.yaml

---

labvm/services/serviceUpdater.yml
labvm/services/sslUpdater/sslUpdater.py
labvm/services/sslUpdater/sslUpdater.service

This service script will check the current CVP SSL cert and renew it if it is set to expire within 14 days.
Steps/Cmds for testing on a new ATD topo:
1. Log into CVP and check the current Cert (for verification purposes)
2. SSH into the jumphost and get into bash, then run the following commands:
```
sudo su
cd /tmp/atd
git checkout -b service-ssl-cert origin/service-ssl-cert
python labvm/services/sslUpdater/sslUpdater.py
```
3. Check CVP to verify new cert has been created.

Service ssl cert

---

topologies/routing/Routing.yml

Updates the routing build topo to the suggested parameters for deployments.

updated routing topo yaml based on suggestions

---

topologies/routing/Routing.yml

updating vEOS version for ratd.

bumping ratd veos version to 4.22.2.1F

---

topologies/routing/Routing.yml

updating the routing topo build file for new parameters.

updating ratd topo yaml for new build parameters

---

topologies/routing/configlets/BaseIPv4_EOS1
topologies/routing/configlets/BaseIPv4_EOS10
topologies/routing/configlets/BaseIPv4_EOS11
topologies/routing/configlets/BaseIPv4_EOS12
topologies/routing/configlets/BaseIPv4_EOS13
topologies/routing/configlets/BaseIPv4_EOS14
topologies/routing/configlets/BaseIPv4_EOS15
topologies/routing/configlets/BaseIPv4_EOS16
topologies/routing/configlets/BaseIPv4_EOS17
topologies/routing/configlets/BaseIPv4_EOS18
topologies/routing/configlets/BaseIPv4_EOS19
topologies/routing/configlets/BaseIPv4_EOS1_RING
topologies/routing/configlets/BaseIPv4_EOS2
topologies/routing/configlets/BaseIPv4_EOS20
topologies/routing/configlets/BaseIPv4_EOS2_RING
topologies/routing/configlets/BaseIPv4_EOS3
topologies/routing/configlets/BaseIPv4_EOS3_RING
topologies/routing/configlets/BaseIPv4_EOS4
topologies/routing/configlets/BaseIPv4_EOS4_RING
topologies/routing/configlets/BaseIPv4_EOS5
topologies/routing/configlets/BaseIPv4_EOS5_RING
topologies/routing/configlets/BaseIPv4_EOS6
topologies/routing/configlets/BaseIPv4_EOS6_RING
topologies/routing/configlets/BaseIPv4_EOS7
topologies/routing/configlets/BaseIPv4_EOS8
topologies/routing/configlets/BaseIPv4_EOS9
topologies/routing/files/cvp/cvp_info.yaml

Removing old TerminAttr version from Pre-Grant, and applying the newer Grant TerminAttr to cvp_info.

removed old TerminAttr string with new for ratd

---

topologies/datacenter-latest/Datacenter.yml

Testing out 4.23.1F per EOS+ teams recommendation.

test dc latest with 4.23.1f

---

topologies/routing/Routing.yml

Updating the routing topo to use 4.23.1F.

upgrading veos ratd to 4.23.1F

---

topologies/datacenter-latest/configlets/BaseIPv4_Leaf1
topologies/datacenter-latest/configlets/BaseIPv4_Leaf2
topologies/datacenter-latest/configlets/BaseIPv4_Leaf3
topologies/datacenter-latest/configlets/BaseIPv4_Leaf4
topologies/datacenter-latest/configlets/BaseIPv4_Spine1
topologies/datacenter-latest/configlets/BaseIPv4_Spine2
topologies/datacenter-latest/configlets/Host1-ATD
topologies/datacenter-latest/configlets/Host2-ATD
topologies/datacenter-latest/files/MenuOptions.yaml
topologies/datacenter-latest/labguides/source/l2evpn.rst
topologies/datacenter-latest/labguides/source/l3evpn.rst
topologies/datacenter-latest/labguides/source/mlag.rst
topologies/datacenter-latest/labguides/source/vxlan.rst

Fixes #84 
This change includes comments received from Joris as he went through the ATD.

Patch latest labs

---

topologies/all/login.py

Fixes #110 
Added check to sort nodes if it is not a standard datacenter topo.

fixes sorting issue in dc-latest topo

---

topologies/all/login.py

created quick fix to allow for null entry (just pressing enter) without disconnecting ssh.
Line 165 start:
elif ans == "":
ans = True
break

Login menu issue 125

---

topologies/datacenter-latest/Datacenter.yml
topologies/routing/Routing.yml

Updating the versions for routing and dc latest topos.

Topo ver updates

---

labvm/services/atdFiles/atdFiles.service
labvm/services/atdServiceUpdater/atdServiceUpdater.service
labvm/services/cvpUpdater/cvpUpdater.service
labvm/services/gitConfigletSync/gitConfigletSync.service
labvm/services/sslUpdater/sslUpdater.service

Reverts aristanetworks/atd-public#131

Revert "fixed service script requirements field and disabling timeouts"

---

topologies/available_topo.yml

Added a true/false Topology_Default tag to allow ATD Team to set the default Blueprint.
Just set Topology_Default: true for the desired default blueprint.

Added Topology_Default tag to available_topo.yml

---

topologies/all/ConfigureTopology.py

configure topology is still running in 2.7, so this change to "raw_input" should fix the bug. The next version of the backend is in python3 and will maintain this bug fix in that way instead.

bug #167 fix

---

topologies/beta-datacenter/labguides/source/cvp_configlet.rst
topologies/datacenter-latest/labguides/source/cvp_configlet.rst

Fixed minor issues with lab step description

---

labvm/services/labModule/labModule.py
labvm/services/labModule/labModule.service
labvm/services/serviceUpdater.yml

This PR creates a new service script that will update the EOS nodes via Configure Topology based on a `default_lab` tag added into `ACCESS_INFO.yaml`

Mod script

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

This adds a development container environment. This container environment will create a baseline dev environment for everyone to work off of. It includes any necessary packages and interpreters to be installed, without modifying the base os.
Required VSCode extension: **ms-vscode-remote.remote-containers**

adding devcontainer

---

labvm/services/atdFiles/atdFiles.sh
labvm/services/cvpUpdater/cvpUpdater.py
labvm/services/cvpUpdater/cvpUpdater.service
labvm/services/gitConfigletSync/gitConfigletSync.py
labvm/services/gitConfigletSync/gitConfigletSync.service
topologies/all/ConfigureTopology.py

Good to go now, gitConfigletSync python3 now as well

No cvp prov

---

.devcontainer/Dockerfile

added these items to the Dockerfile, looks good?

added Sphinx and sphinx-bootstrap-theme to Dockerfile

---

topologies/datacenter-latest/labguides/source/ucn-l2evpn.rst
topologies/datacenter-latest/labguides/source/ucn-l3evpn.rst
topologies/datacenter-latest/labguides/source/ucn-l3ls.rst
topologies/datacenter-latest/labguides/source/ucn-mlag.rst
topologies/datacenter-latest/labguides/source/ucn-vxlan.rst

added notes to ucn guides

---

labvm/services/atdFiles/atdFiles.sh

Added a while wait check in atdFiles to wait until ACCESS_INFO.yaml is available.

added while wait check until ACCESS INFO file is there

---

labvm/services/atdFiles/atdFiles.service
labvm/services/atdServiceUpdater/atdServiceUpdater.py
labvm/services/atdServiceUpdater/atdServiceUpdater.service
labvm/services/cvpUpdater/cvpUpdater.service
labvm/services/gitConfigletSync/gitConfigletSync.service
labvm/services/labModule/labModule.service
labvm/services/serviceUpdater.yml
labvm/services/sslUpdater/sslUpdater.service

Summary:
Update to `atdServiceUpdater`:
- .py: updates how it handles updates and the order of service scripts. Updates and restarts atdServiceUpdater first before doing any work on other scripts.
- .service: add a 900 second timeout
Updates to:
- atdFiles.service: Removes dependency for `atdServiceUpdater` to complete first
- All other service files wait for `atdFiles.sh` to complete before starting.

Rob service update

---

labvm/services/cvpUpdater/cvpUpdater.service
labvm/services/gitConfigletSync/gitConfigletSync.service
labvm/services/labModule/labModule.service
labvm/services/sslUpdater/sslUpdater.service

Removed requires filed from service file.

removed requires from service file.

---

topologies/beta-routing/topo_build.yml

Just bumping the vEOS version the beta-ratd only.

Increasing vEOS version to Lima

---

labvm/services/atdFiles/atdFiles.sh

Updating the atdFiles for a new jump host build. The new jumphost will install the additional python and apt packages ahead of time.

updated atdFiles for new jh build

---

labvm/services/atdFiles/atdFiles.sh

Reverts aristanetworks/atd-public#206

Revert "updated atdFiles for new jh build"

---

labvm/services/atdFiles/atdFiles.sh

Removed some npm installs as they will be included already in the jumphost build.

removed some npm installs

---

nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/nginx/src/atd.conf

Add Robot container for ATD test automation
Add Ansible AVD/CVP for Ansible demos

Nested release robot ansible

---

.devcontainer/Dockerfile

Adding GitHub CLI to the devcontainer

adding GitHub CLI to devcontainer

---

labvm/services/gitConfigletSync/gitConfigletSync.service
topologies/all/ConfigureTopology.py
topologies/all/login.py

Added check for tasks in progress before lab executions:
```
What would you like to do?: 2
Starting deployment for Datacenter - mlag lab...
Tasks are currently executing. Waiting 10 seconds...
Tasks are currently executing. Waiting 10 seconds...
Tasks are currently executing. Waiting 10 seconds...
Tasks are currently executing. Waiting 10 seconds...
Tasks are currently executing. Waiting 10 seconds...
Tasks are currently executing. Waiting 10 seconds...
Tasks are currently executing. Waiting 10 seconds...
Tasks are currently executing. Waiting 10 seconds...
Gathering task information...
Waiting on change control to finish executing...
Lab Setup Completed. Please press Enter to continue...
```

Login menu task check

---

nested-labvm/atd-docker/docker-compose.yml
topologies/datacenter/files/.ansible.cfg
topologies/datacenter/labguides/source/ansible_and_jinja_templates.rst
topologies/datacenter/labguides/source/day2_operations.rst

Let me know if you find any loose ends that were missed. I didn't preview the labguide so there may be changes needed when the html is rendered that I will catch on the next testing.

N ch programmability review

---

nested-labvm/atd-docker/coder/Dockerfile
nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/docker_build.sh
nested-labvm/atd-docker/login/Dockerfile

Kvm console access

---

nested-labvm/atd-docker/coder/Dockerfile
nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/docker_build.sh
nested-labvm/atd-docker/login/Dockerfile

* added kvm console support in login container
* updated coder from 3.8.0 to 3.9.1 and added virsh console access

Kvm console access (#264)

---

nested-labvm/services/atdUpdate/atdUpdate.sh

Atdupdate git

---

nested-labvm/services/atdUpdate/atdUpdate.sh

* refactored git sync in atdUpdate
* added messaging and update git branch
* adding fetch
* updated git branch to show current instead of parsing output
* updating not logic for corey

Atdupdate git (#275)

---

topologies/datacenter/configlets/Host2-Media
topologies/datacenter/configlets/media-leaf1-Multicast-Lab
topologies/datacenter/configlets/media-leaf4-Multicast-Lab-Completed
topologies/datacenter/configlets/media-spine1-Multicast-Lab
topologies/datacenter/configlets/media-spine2-Multicast-Lab
topologies/datacenter/labguides/source/media-multicast.rst

N multi sfe

---

topologies/datacenter/configlets/Host2-Media
topologies/datacenter/configlets/media-leaf1-Multicast-Lab
topologies/datacenter/configlets/media-leaf4-Multicast-Lab-Completed
topologies/datacenter/configlets/media-spine1-Multicast-Lab
topologies/datacenter/configlets/media-spine2-Multicast-Lab
topologies/datacenter/labguides/source/media-multicast.rst

* updated multicast routing for media labs for new syntax and sfe
* updated media labguide for sfe config and note

N multi sfe (#284)

---

nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/labguides/src/build_labguides.sh

force pdf labguides to generate

---

nested-labvm/atd-docker/coder/Dockerfile
nested-labvm/atd-docker/docker-compose.yml

* added shyaml to Dockerfile for atd-coder
* changed atd-coder to image tag 2.0.1

Avd atd 2021.1 ch (#305)

---

topologies/training-level4/configlets/DCI-BASE
topologies/training-level4/configlets/OOB-CORE-BASE
topologies/training-level4/configlets/OOB-DC1-BASE
topologies/training-level4/configlets/OOB-DC2-BASE
topologies/training-level4/configlets/SW1-DC3-BASE
topologies/training-level4/configlets/core1-ISP1-BASE
topologies/training-level4/configlets/core1-ISP2-BASE
topologies/training-level4/configlets/core2-ISP1-BASE
topologies/training-level4/configlets/core2-ISP2-BASE
topologies/training-level4/configlets/host1-DC1-BASE
topologies/training-level4/configlets/host1-DC2-BASE
topologies/training-level4/configlets/host1-DC3-BASE
topologies/training-level4/configlets/host2-DC1-BASE
topologies/training-level4/configlets/host2-DC2-BASE
topologies/training-level4/configlets/internet-BASE

* enabled multi-agent on select devices
* updated host configs

L4 cfgs update (#316)

---

nested-labvm/atd-docker/cloud-builds/conftopo.yaml
nested-labvm/atd-docker/confTopo/Dockerfile
nested-labvm/atd-docker/confTopo/src/ConfigureTopology/ConfigureTopology.py
nested-labvm/atd-docker/confTopo/src/confTopo.py
nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/uilanding/Dockerfile
nested-labvm/atd-docker/uilanding/src/html/index.html
nested-labvm/atd-docker/uilanding/src/html/js/atd-ws.js
nested-labvm/atd-docker/uilanding/src/uilanding.py

This PR adds a new Conftopo application. It is laying the groundwork to be an internal API endpoint to configure the topology for different lab modules. As a start, it can check the status of CVP and any tasks.
UIlanding app has been updated with websocket support for querying conftopo to get the status of CVP and any tasks. Then to display them on the landing page.

CVP Status

---

nested-labvm/atd-docker/cloud-builds/conftopo.yaml
nested-labvm/atd-docker/confTopo/Dockerfile
nested-labvm/atd-docker/confTopo/src/ConfigureTopology/ConfigureTopology.py
nested-labvm/atd-docker/confTopo/src/confTopo.py
nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/uilanding/Dockerfile
nested-labvm/atd-docker/uilanding/src/html/index.html
nested-labvm/atd-docker/uilanding/src/html/js/atd-ws.js
nested-labvm/atd-docker/uilanding/src/uilanding.py

* initial conftopo
* adding some logic
* created backend check for cvp status, created websocket for uilanding to display and check the status of CVP
* bumping uilanding to Python 3.9
* updated conftopo CVP status to Starting when not available
* added check for cvp tasks
* updated logic for uilanding and conftopo
* added updated app builds

CVP Status (#386)

---

nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/uilanding/src/html/index.html
nested-labvm/atd-docker/uilanding/src/html/js/atd-ws.js
nested-labvm/atd-docker/uilanding/src/uilanding.py

Added the topology countdown timer to uilanding. Alerts user when less than 30 minutes remains.

added countdown timer to uilanding

---

nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/login/Dockerfile
nested-labvm/atd-docker/login/src/resetVMs.py

* updated python version and added jsonrpclib
* reset coder dockerfile and updated login
* updated compose version for coder

Dock p3 json (#394)

---

topologies/base_topo.yml

Adding training team level 3 and level 5 to prod

Train update

---

topologies/datacenter/labguides/source/cvp_configlet.rst

Update alias command

---

topologies/datacenter/labguides/source/cvp_configlet.rst

Update alias command (#459)

---

topologies/datacenter/labguides/source/cvp_configlet.rst

updated alias commands

---

nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/login/Dockerfile
nested-labvm/atd-docker/login/src/saveRunning.py
nested-labvm/atd-docker/login/src/uploadExam.py

Co-authored-by: richardap1 <richard.parkin@gmail.com>

Update exam scripts, add save script in login container (#482)

---

topologies/training-level1/configlets/ATD-INFRA
topologies/training-level2/configlets/ATD-INFRA
topologies/training-level3-exam/configlets/ATD-INFRA
topologies/training-level3/configlets/ATD-INFRA
topologies/training-level5/configlets/ATD-INFRA
topologies/training-level5/configlets/core1-ISP2-BASE
topologies/training-level5/files/ceos/CVX/startup-config
topologies/training-level5/files/ceos/DCI/startup-config
topologies/training-level5/files/ceos/OOB-CORE/startup-config
topologies/training-level5/files/ceos/OOB-DC1/startup-config
topologies/training-level5/files/ceos/OOB-DC2/startup-config
topologies/training-level5/files/ceos/SW1-DC3/startup-config
topologies/training-level5/files/ceos/core1-isp1/startup-config
topologies/training-level5/files/ceos/core1-isp2/startup-config
topologies/training-level5/files/ceos/core2-isp1/startup-config
topologies/training-level5/files/ceos/core2-isp2/startup-config
topologies/training-level5/files/ceos/host1-DC1/startup-config
topologies/training-level5/files/ceos/host1-DC2/startup-config
topologies/training-level5/files/ceos/host1-DC3/startup-config
topologies/training-level5/files/ceos/host2-DC1/startup-config
topologies/training-level5/files/ceos/host2-DC2/startup-config
topologies/training-level5/files/ceos/internet/startup-config

* Update training configlets for multiagent
* fixed mask

N update configlet for nested (#487)

---

nested-labvm/atd-docker/ceosbuilder/ceosbuilder.py
nested-labvm/atd-docker/docker-compose.yml

* added parsing for "s1-" or "s2-" to function parseNames in ceosbuilder.py
* added new tag for new ceosbuilder build

Ceos multi (#491)

---

topologies/base_topo.yml

Wait until 10-29-2021 to merge in this PR.

ATD Imperial and 2021.1 release update

---

topologies/base_topo.yml

Updated all topos for training topologies for updated CVP install

Updated Train Dev

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitignore
nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/labguides/Dockerfile

* Updated labguides container for thumbnails
* Updated labguides container:
- Added ability for copy button on any code blocks
* updated docker compose file:
- Updated labguides container image to 2.0.2

Labguides cnt update (#531)

---

topologies/training-level1/topo_build.yml
topologies/training-level2/topo_build.yml
topologies/training-level3-2/topo_build.yml
topologies/training-level3-exam/topo_build.yml
topologies/training-level3/topo_build.yml
topologies/training-level4/files/cvp/cvp_info.yaml
topologies/training-level4/topo_build.yml
topologies/training-level5/files/cvp/cvp_info.yaml
topologies/training-level5/topo_build.yml
topologies/training-level7/files/cvp/cvp_info.yaml
topologies/training-level7/topo_build.yml

- Updated CVP CPU resources in training topologies
- Removed CVX from levels 4, 5 and 7

Update to Training topos:

---

nested-labvm/atd-docker/coder/src/vs-extensions.txt
topologies/dual-datacenter/files/apps/coder/AristaValidatedDesigns/readme.md

Updated VS code extension file and created preliminary folder for IDE to store the the AVD files for the dual-dc topology

update vscode extension and AVD folder on IDE

---

topologies/datacenter/labguides/source/EVPN_Class_Guide.rst
topologies/datacenter/labguides/source/conf.py
topologies/datacenter/labguides/source/cvp_cc.rst
topologies/datacenter/labguides/source/cvp_configlet.rst
topologies/datacenter/labguides/source/cvx.rst
topologies/datacenter/labguides/source/l2evpn.rst
topologies/datacenter/labguides/source/l3evpn.rst
topologies/datacenter/labguides/source/l3ls.rst
topologies/datacenter/labguides/source/media-IP_Intro.rst
topologies/datacenter/labguides/source/media-STP_SVI.rst
topologies/datacenter/labguides/source/media-bgp.rst
topologies/datacenter/labguides/source/media-multicast.rst
topologies/datacenter/labguides/source/media-ospf.rst
topologies/datacenter/labguides/source/mlag.rst
topologies/datacenter/labguides/source/vxlan.rst

Updated lab-guides for Datacenter topology (Thumbnail)

Cc lab guides

---

topologies/datacenter/labguides/source/EVPN_Class_Guide.rst
topologies/datacenter/labguides/source/conf.py
topologies/datacenter/labguides/source/cvp_cc.rst
topologies/datacenter/labguides/source/cvp_configlet.rst
topologies/datacenter/labguides/source/cvx.rst
topologies/datacenter/labguides/source/l2evpn.rst
topologies/datacenter/labguides/source/l3evpn.rst
topologies/datacenter/labguides/source/l3ls.rst
topologies/datacenter/labguides/source/media-IP_Intro.rst
topologies/datacenter/labguides/source/media-STP_SVI.rst
topologies/datacenter/labguides/source/media-bgp.rst
topologies/datacenter/labguides/source/media-multicast.rst
topologies/datacenter/labguides/source/media-ospf.rst
topologies/datacenter/labguides/source/mlag.rst
topologies/datacenter/labguides/source/vxlan.rst

* Update Lab-guides for thumbnails in Datacenter topology

Cc lab guides (#542)

---

topologies/datacenter/labguides/source/cvp_cc.rst

updated CVP lab guides for the Jackson release

Dc jackson labguides

---

topologies/base_topo.yml

- dual-dc in dev
- dc  in dev and prod for cEOS and vEOS
- ratd in dev and prod for cEOS and vEOS

Updated 2021.3 Images:

---

nested-labvm/services/atdStartup/atdStartup.sh

added logic to check and see if docker config exists, if not set it.

Updated startup script;

---

topologies/dual-datacenter/labguides/source/cvp_cc.rst
topologies/routing/configlets/BaseIPv4_EOS10_BARE
topologies/routing/configlets/BaseIPv4_EOS11_BARE
topologies/routing/configlets/BaseIPv4_EOS12_BARE
topologies/routing/configlets/BaseIPv4_EOS13_BARE
topologies/routing/configlets/BaseIPv4_EOS14_BARE
topologies/routing/configlets/BaseIPv4_EOS15_BARE
topologies/routing/configlets/BaseIPv4_EOS16_BARE
topologies/routing/configlets/BaseIPv4_EOS17_BARE
topologies/routing/configlets/BaseIPv4_EOS18_BARE
topologies/routing/configlets/BaseIPv4_EOS19_BARE
topologies/routing/configlets/BaseIPv4_EOS1_BARE
topologies/routing/configlets/BaseIPv4_EOS20_BARE
topologies/routing/configlets/BaseIPv4_EOS2_BARE
topologies/routing/configlets/BaseIPv4_EOS3_BARE
topologies/routing/configlets/BaseIPv4_EOS4_BARE
topologies/routing/configlets/BaseIPv4_EOS5_BARE
topologies/routing/configlets/BaseIPv4_EOS6_BARE
topologies/routing/configlets/BaseIPv4_EOS7_BARE
topologies/routing/configlets/BaseIPv4_EOS8_BARE
topologies/routing/configlets/BaseIPv4_EOS9_BARE
topologies/routing/files/menus/Mesh-Topology-EVPN-Labs.yaml

adding the bare interface configs - along with changes to the Mesh-Topology-EVPN-Labs.yaml file to include the new menu option. I thought the cvp_cc.rst was already included in my last commit.

Ratd bare configs

---

topologies/datacenter/labguides/Makefile
topologies/datacenter/labguides/source/cvp_studios_l3ls_evpn.rst

* Update cvp_studios_l3ls_evpn.rst
* Update cvp_studios_l3ls_evpn.rst
* Edit
* Formatting Fixes

Arista scriv cvp studios l3ls evpn (#578)

---

topologies/dual-datacenter/configlets/TSHOOT_s1-host1_intro
topologies/dual-datacenter/configlets/TSHOOT_s1-leaf1_intro
topologies/dual-datacenter/configlets/TSHOOT_s1-leaf2_intro
topologies/dual-datacenter/configlets/TSHOOT_s1-spine1_intro
topologies/dual-datacenter/labguides/source/tshoot-intro.rst

Updated interface descriptions and intro labguide for new naming convention

Updated TShoot labs for Dual-DC

---

nested-labvm/atd-docker/docker-compose.yml

Rebuild of login and conftopo container images for newer cvprac 1.2.0 release

Container Updates:

---

topologies/dual-datacenter/files/menus/Data-Center-Labs.yaml

- Fixed reset command for additional bash command that was referencing an invalid file
- Fixed formatting for studiosl3ls

patched dual dc menu: (#621)

---

topologies/dual-datacenter/labguides/source/cvp_studios_l3ls_evpn.rst

* Dual Data Center Studios Changes
* DDC Update2
* DDC Update3
* Update cvp_DDC_studios_l3ls_evpn.rst
* Rewrite for formatting
* Update index.rst
* minor change for formatting

Scriv ddc l3lsevpn studios (#635)

---

nested-labvm/atd-docker/cloud-builds/vtepinfo.yaml
nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/docker_run.sh
nested-labvm/atd-docker/monitor/src/atdMonitor.py
nested-labvm/atd-docker/uilanding/src/uilanding.py
nested-labvm/atd-docker/vtepinfo/Dockerfile
nested-labvm/atd-docker/vtepinfo/src/vtepinfo.py
nested-labvm/services/cvpStartup/cvpStartup.sh
nested-labvm/services/cvpUpdate/cvpUpdate.sh
nested-labvm/services/eosStartup/eosStartup.sh
nested-labvm/services/eosUpdate/eosUpdate.sh
topologies/base_topo.yml

- adding new eos and cvp update and startup scripts
- updated startup to reference docker_run script
- added new vtepinfo container app
- updated base_topo for new structure on 2022.2.0
- updated docker_run
- updated dual v2 images
- added more logic to cvpStartup
- updated nodes disk image size
- updated branch for dual deploy testing
- updated schema name
- update vtepinfo for more logging
- fixed brctl command in vtepinfo;
- updated docker run
- fixed url calls for vtep
- added schema check in uilanding
- updated monitor for handling new schema
- added schema 1 to non converted topos

dual deploy

---

nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/gitConfigletSync/src/gitConfigletSync.py

- Added check for failed tasks after inital execution. Executes failed tasks

Patched gitconfigletsync: (#664)

---

topologies/datacenter/labguides/source/day2_operations.rst
topologies/datacenter/labguides/source/rollback.rst
topologies/dual-datacenter/labguides/source/day2_operations.rst
topologies/dual-datacenter/labguides/source/rollback.rst

* Corrected playbook state settings and minor verbage
* Updating dual DC as well

Corrected playbook state settings and minor verbage in lab guide (#670)

---

topologies/dual-datacenter/files/menus/Troubleshooting-Labs.yaml

* Update Troubleshooting-Labs.yaml
* Update Troubleshooting-Labs.yaml

Update Troubleshooting-Labs.yaml (#684)

---

topologies/dual-datacenter/files/menus/Troubleshooting-Labs.yaml

Scriv t shoot scenario 1

---

topologies/dual-datacenter/files/menus/Troubleshooting-Labs.yaml

* Update Troubleshooting-Labs.yaml
* Update Troubleshooting-Labs.yaml
* Update Troubleshooting-Labs.yaml
SPACES

Scriv t shoot scenario 1 (#686)

---

nested-labvm/atd-docker/coder/Dockerfile
nested-labvm/atd-docker/docker-compose.yml

List of changes:
- coder version from 4.7.0 to 4.9.1
- silence agent pid XXX message
- clean unnecessary files after apt install (slightly reduces the size)
- disable pip version check
- remove upgrade pip as it's irrelevant with apt install
- add pip install flags to reduce container size
- no sudo for pip
- set user path correctly
Some testing done locally. But please test carefully before merging due to significant number of changes.

Coder container fixes

---

nested-labvm/atd-docker/coder/Dockerfile
nested-labvm/atd-docker/docker-compose.yml

* silence agent pid xxx
* clean temp files after apt install
* bump code server to 4.9.1
* add --no-cache-dir to pip install to reduce size
* remove upgrade pip as it's not required
* remove pip version check
* remove sudo as pip must not be executed as root
* bring back sudo as it breaks ansible-galaxy
* set user and env vars correctly
* merge more commands into a single RUN
* set workdir instead of volume
* update coder image tag in compose

Coder container fixes (#681)

---

nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/nginx/src/atd.conf

added additional paths for new cvp paths

updated nginx conf (#691)

---

topologies/dual-datacenter/labguides/source/cvp_studios_l3ls_evpn.rst
topologies/dual-datacenter/labguides/source/tshoot-intro.rst

* Update Troubleshooting-Labs.yaml
* Update Troubleshooting-Labs.yaml
* Update Troubleshooting-Labs.yaml
SPACES
* Update tshoot-intro.rst
Update tshoot doc for correct number
* Update cvp_studios_l3ls_evpn.rst

Scriv t shoot scenario 1 (#690)

---

nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/nginx/src/atd.conf

- Updated nginx config with grpc location pathing
- Increased grpc timeouts for long lived connections
- bumped nginx image version

Updated nginx: (#695)

---

nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/gitConfigletSync/Dockerfile
nested-labvm/atd-docker/gitConfigletSync/src/gitConfigletSync.py

added regen of certs and added cvp volume  mount

updated gitconfiglet (#697)

---

nested-labvm/atd-docker/ceosbuilder/ceosbuilder.py
nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/docker_build_run.sh
topologies/dual-datacenter/ceos_build.yml
topologies/routing/ceos_build.yml

- rewrite for ceosbuilder
- updated ceosbuilder
- topo name update
- removing ceosbuilder from compose
- updated ceos name in builder
- adding mtu adjust to ceosbuilder
- updating ceosbuild
- updates to ceosbuilder dev name
- adding new docker build run script to be used during image builds
- updated routing build file
- updated ceos build script

rm rlab ceos

---

nested-labvm/atd-docker/ceosbuilder/ceosbuilder.py
nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/docker_build_run.sh
topologies/dual-datacenter/ceos_build.yml
topologies/routing/ceos_build.yml

* rewrite for ceosbuilder
* updated ceosbuilder
* topo name update
* removing ceosbuilder from compose
* updated ceos name in builder
* adding mtu adjust to ceosbuilder
* updating ceosbuild
* updates to ceosbuilder dev name
* adding new docker build run script to be used during image builds
* updated routing build file
* updated ceos build script

rm rlab ceos (#742)

---

nested-labvm/atd-docker/coder/Dockerfile
nested-labvm/atd-docker/docker-compose.yml

- Updated Coder to 4.14.1\n- Updated AVD in Coder to 4.1.0\n- Updated CVP Collection in Coder to 3.6.0

Updated Coder Container

---

nested-labvm/atd-docker/coder/Dockerfile
nested-labvm/atd-docker/docker-compose.yml

Updated Coder container to leverage cvp_collections version 3.7

Updated Coder Collections

---

topologies/dual-datacenter/files/apps/coder/labfiles/lab4/lab4-advanced-playbook.yml
topologies/dual-datacenter/labguides/source/ansible_and_jinja_templates.rst

- Updated ansible_connection to correct httpapi

Fix Dual-DC Ansible Lab

---

nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/nautobot/nautobot_config.py
nested-labvm/atd-docker/nautobot/nbot-local.env
nested-labvm/atd-docker/nautobot/uwsgi.ini
nested-labvm/atd-docker/nginx/Dockerfile
nested-labvm/atd-docker/nginx/src/atd.conf
nested-labvm/atd-docker/uilanding/src/html/index.html

* nautobot nginx and docker configs
* nautobot nginx and docker configs - updates
* ssh timeout set to 600
* removed newline at end
* updated for push to branch
* updates to get it running
* Updating docker compose with new container builds for uilanding and nginx
* added volume mounts for nbot worker and beat
* udpates to nbot
* updating nginx conf for a few natutobot paths
* updated nginx paths and added proxy_redirect to nautobot location
* test removal of redirect
* adding redirect
---------
Co-authored-by: Rob Martin <robmartin@arista.com>

Ch nautobot deploy part2 (#758)

---

nested-labvm/atd-docker/nginx/src/atd.conf

- Added assets path to the cv app

Updated Nginx path: (#764)

---

nested-labvm/atd-docker/coder/Dockerfile
nested-labvm/atd-docker/docker-compose.yml

Upgrades to coder container image:
- code-server to 4.17.1
- AVD collection to 4.4.0
- CVP collection to 3.8.0

Upgraded Coder Container

---

nested-labvm/atd-docker/coder/Dockerfile
nested-labvm/atd-docker/docker-compose.yml

- code-server to 4.17.1
- AVD to 4.4.0
- CVP to 3.8.0

Upgraded Coder Container: (#768)

---

nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/kvmbuilder/src/kvm-topo-builder.py

* Updates to kvmbuilder
* updates to generated mac

Updates to kvmbuilder (#776)

---

topologies/training/labguides/source/ansible_adhoc_and_simple_playbooks.rst
topologies/wan/files/apps/coder/labfiles/lab4/lab4-advanced-playbook.yml

Add a short term fix to the lab guide and the playbook.

Facelift ansible playbook

---

topologies/training/labguides/source/ansible_adhoc_and_simple_playbooks.rst
topologies/wan/files/apps/coder/labfiles/lab4/lab4-advanced-playbook.yml

* fix playbook
* fix the document

Facelift ansible playbook (#792)

---

topologies/dual-datacenter/files/apps/coder/labfiles/lab4/lab4-advanced-playbook.yml
topologies/dual-datacenter/labguides/source/ansible_adhoc_and_simple_playbooks.rst

updates to fix where previous PR changes were misplaced.

updated labguides for proamability fixes

---

nested-labvm/atd-docker/cvpUpdater/src/cvpUpdater.py
nested-labvm/atd-docker/docker-compose.yml
topologies/campus/ceos_build.yml
topologies/dual-datacenter/ceos_build.yml
topologies/routing/ceos_build.yml

- Updates to ceos_buid file for cv manage
- Updated cv_manage value param
- Updated cvupdater for new formattting statements and build files
- added some extra debugs
- Updates to cvp updater
- Updates
- Updated cvpupdater

cvp manage

---

topologies/dual-datacenter/labguides/source/l3ls.rst

Fixed a few steps in the "Other BGP" section to be a bit more clear as to what the student should do.  Also added some notes that clarify that the commands are just examples and might not "work" since the rest of the lab isn't configured to match.

Slight edits to BGP commands in Guide.

---

nested-labvm/atd-docker/nginx/src/atd.conf

Updates made to nginx config to allow larger file uploads

Updates to nginx max file

---

nested-labvm/atd-docker/docker-compose.yml
nested-labvm/atd-docker/jenkins/Dockerfile

Updated Jenkins to a newer lts of jdk17

Updated Jenkins build to jdk17

---

nested-labvm/atd-docker/coder/Dockerfile

- Update ansible-core version
- Update AVD installation method using pyavd target
- Add ANTA

AVD coder updates

---

nested-labvm/atd-docker/coder/Dockerfile
nested-labvm/atd-docker/docker-compose.yml

- **Updating coder container**
- **Updated coder dockerfile for cvp version**
- **AVD coder updates (#841)**
- **cleanup pip installs and allow breaking system packages (#842)**
- **Updated docker-compose with updated Coder version**

coder update
