aristanetworks/atd-public

- labguides/source/conf.py
- labguides/source/connecting.rst
- labvm/services/atdFiles/atdFiles.service
- labvm/services/atdFiles/atdFiles.sh
- labvm/services/atdServiceUpdater/atdServiceUpdater.py
- labvm/services/atdServiceUpdater/atdServiceUpdater.service
- labvm/services/gitConfigletSync/gitConfigletSync.py
Re-org'd the service files so the atdServiceUpdater.py file clones the atd-public repo and saves it to /tmp/atd/ directory. It will keep this directory here and not remove it. All of the other service files will reference /tmp/atd/ for any repo related information it needs.
Also fixed an issue where atdFiles.sh was removing the /home/arista directory.
> Updating service files

- labguides/source/programmability_connecting.rst
- labvm/services/atdFiles/atdFiles.service
- labvm/services/atdFiles/atdFiles.sh
Found the `programmability_connecting.rst` labguide to reference the arista user to access via ssh.  Added in the `{REPLACE_PWD}` placeholder in the labguide, and added the `sed` cmd to update the password in the `atdFiles.sh` file.
> Labguide arista

- labvm/services/atdFiles/atdFiles.sh
- topologies/all/login.py
- topologies/datacenter/files/Broadcaster/pushHostMediaConfig.sh
Fixes #21 
Adds screen option back to the main login.py landing menu
Fixes #29 
Updated atdFiles.sh to perform an `rsync` instead of `cp`.  With `rsync` it will copy hidden files which now brings over the `.screenrc` file.
> Atd files patch

- topologies/all/login.py
The `devicecount` variable would get set the incorrect value in the `media` module.  In the `media` module, it would be set to the amount of media lab options and not device count.  I moved the setting for `devicecount` to right after the devices get counted and displayed on screen.
> Corrected device count var

- topologies/all/login.py
Fixes #40
This corrects an issue where `login.py` would crash when trying to load on the routing topology.
This also sorts the routing topology device list based off alphanumeric on device name.
> Rob login patch

- topologies/all/ConfigureTopology.py
- topologies/datacenter/configlets/aws-infra
- topologies/routing/configlets/aws-infra
- topologies/routing/files/cvp/cvp_info.yaml
Creating the `aws-infa` configlet to be applied to the ATDs.  According to @dathelen this cmd will prevent the logs from filling up due to the PhyEthtool agent crashing. 
> PhyEthTool repeatedly crashes on veos running in AWS
> Cfg aws update

- topologies/all/ConfigureTopology.py
In the routing topology, when a lab control option is pushed, the device loses it's mgmt IP address since the `BaseIPv4_` configlet is removed.  In doing so makes the device inaccessible.
This PR adds `BaseIPv4_` configlets as a standard configlet to remain.
> Adding BaseIPv4 to standard routing configlet

- topologies/datacenter/labguides/source/l3ls.rst
Added traceroute and IP check to L3LS verification.  Optional step to force traffic through Leaf4 if needed.  Should satisfy [issue#25](https://github.com/aristanetworks/atd-public/issues/25)
> added L3LS verification enhancement

- topologies/datacenter-latest/Datacenter.yml
Downgrading vEOS to 4.22.2.1F to see if deployments will succeed.
> DC-latest testing for vEOS versions

- topologies/routing/Routing.yml
Bumping the CVP version to 2019.1.1, due to 2018.2.2 not being avail for deployments in RATD.
> bumping CVP version in RATD to 2019.1.1

- labvm/services/gitConfigletSync/gitConfigletSync.py
Fixes #23 
Service script starts referencing rcvpapi and leverages it to import/update static and configlet builders into CVP.
> Git configlet builder

- topologies/datacenter-latest/Datacenter.yml
There is either an issue with the AMI, or vEOS node when the topology reboots.  Downgrading the vEOS version for testing purposes.
> bumping dc latest veos to 4.22.2f

- topologies/datacenter-latest/Datacenter.yml
Version 4.22.2F showed the same behavior on node reboot.  Testing 4.22.0F.
> testing 4.22.0f

- topologies/datacenter-latest/Datacenter.yml
Downgrading to 4.21.7M, supposed working release.
> downgrading dc latest veos to 4.21.7m

- topologies/datacenter-latest/Datacenter.yml
Reverting the datacenter-latest topo back to 4.22.2.1F.
> reverting dc latest veos version to 4.22.2.1F

- topologies/all/ConfigureTopology.py
- topologies/datacenter-latest/configlets/Host1-ATD
- topologies/datacenter-latest/configlets/Host1-Media
- topologies/datacenter-latest/configlets/Host2-ATD
- topologies/datacenter-latest/configlets/Host2-Media
- topologies/datacenter-latest/files/MenuOptions.yaml
- topologies/datacenter-latest/files/cvp/cvp_info.yaml
Fixes #95 
Fixed an issue where the host devices in the `datacenter-latest` topo were missing interface level configurations.  Added the configlets for those devices and added the proper mappings for those nodes.
Also added the 'VLANs' configlet used in the `datacenter-latest` topo to a base configlet in `ConfigureTopology.py`
> Patch host cfgs

- topologies/datacenter-latest/configlets/ATD-INFRA
- topologies/routing/configlets/ATD-INFRA
Adding in missing event-handlers that EOS+ configures on vEOS nodes.  This is the cause for the nodes not coming up after a topo spin down/up or reboot.  Also `agent PhyEthtool shutdown` is no longer needed in 4.23.1F.
> Atd infra update

- topologies/datacenter-latest/files/veos-patch.sh
- topologies/datacenter-latest/labguides/source/l2evpn.rst
- topologies/datacenter-latest/labguides/source/l3evpn.rst
This is a temporary fix to install a Kernel patch on the vEOS nodes to prevent the EvpnrtrEncapAgent from crashing.  This script will allow the L2EVPN and L3EVPN labs to be completed successfully.
> Dclatest eos patch

- topologies/datacenter-latest/Datacenter.yml
EOS+ created a patched version of 4.23.0.1F that includes the fix for the EPVN agent from crashing.  This is a test to verify that the patch works on deployments.
> testing patched version of 4.23.0.1F for evpn.

- labvm/services/cvpUpdater/cvpUpdater.py
Fixes #113 
This updates the cvpUpdater script to reboot all vEOS after all the vEOS nodes and CVP has been provisioned.  This will only run if CVP is being provisioned.  This will allow multi-agent to be enabled and can be used in the labs.
> added logic to reboot all veos nodes after CVP provisioning

- topologies/all/ConfigureTopology.py
Fixes #117 
Fixes an issue when the devices weren't getting the base configlets pushed to them via CVP.  To test out on topologies run the following in bash on the jumphost:
```
cd /tmp/atd
sudo su
git checkout topologies
git checkout -b patch-confTopo-reset origin/patch-confTopo-reset
bash labvm/services/atdFiles/atdFiles.sh
exit
exit
```
> Patch conf topo reset

- labvm/services/gitConfigletSync/gitConfigletSync.service
Fixes #79 
In the Routing topology it leverages a cvpUpdater.py to configure and provision a blank CVP for use in the topology.  During initial configuration there is a race between cvpUpdater.py and gitConfigletSync.py and causes an issue with certain configlets from being updated in the future.
This change moves gitConfigletSync.py to be started once cvpUpdater.py has completed running on boot.
> requiring cvpUpdater to complete before config sync

- labvm/services/cvpUpdater/cvpUpdater.service
Increasing the timeout for the cvpUpdater.py script.  In some topologies the script can timeout and restart while it is in the process of configuring devices.  Which could lead to problems with initial deployments.
> increased timeout for cvpUpdater to 15 minutes

- labvm/services/atdFiles/atdFiles.service
- labvm/services/atdServiceUpdater/atdServiceUpdater.service
- labvm/services/cvpUpdater/cvpUpdater.service
- labvm/services/gitConfigletSync/gitConfigletSync.service
- labvm/services/sslUpdater/sslUpdater.service
Fixes an issue where service scripts are not waiting for previous script to complete.  Also sets no timeout for the scripts to complete.  There is a condition when they restart that the original script is still running and multiple processes of the same script are running.  Could cause issues with configuring devices like CVP.
> fixed service script requirements field and disabling timeouts

- topologies/datacenter-latest/files/Broadcaster/mcast-receiver.sh
- topologies/datacenter-latest/files/Broadcaster/mcast-source.sh
added static route mapping lines to multicast source and receiver scripts for the media-mcast lab to function correctly.  Tested manually switching branches and the script works correctly for the lab and the lab functions as expected.
> Fix multicast lab issue145

- topologies/beta-datacenter/topo_build.yml
- topologies/beta-routing/topo_build.yml
Updating CVP to 2020.1.0-EFT6 in the Beta Datacenter topology.  This is for testing of our scripts on the upcoming Green release.
> beta-dc testing green eft6

- topologies/beta-routing/configlets/ATD-INFRA
This is for the beta routing topology only at this time just to get it up and running for testing.
> Changed hash for arista user pw to align with CVP

- topologies/datacenter-latest/configlets/ATD-INFRA
- topologies/routing/configlets/ATD-INFRA
The arista user password hashes weren't updated in routing and datacenter-latest ATD-INFRA configlets. This PR updates the hash to work with the new password.
> updated password has for arista user.

- labvm/services/cvpUpdater/cvpUpdater.py
- labvm/services/cvpUpdater/cvpUpdater.service
`cvpUpdater.service` used to run as the arista user in the past. Since it was changed to the `root` user, the `cvpUpdater.py` script could not ssh to each vEOS node to reboot with the incorrect ssh keys.
For `cvpUpdater.py` service, instead of disabling the `cvpUpdater` service script, which requires root access, we are adding the `.cvpState.txt` file that prevents the script from running in the future.
> fixed user permission and disabling cvpUpdater to fix reboot of nodes

- labvm/services/labModule/labModule.py
- labvm/services/labModule/labModule.service
Added a connection to CVP in order to get all nodes in inventory and perform an `ipConnectivityTest` API call. 
Before `labModule.py` would start after `cvpUpdater.py` completed. When it would start it will provision the nodes in CVP, but at the time to create and execute the tasks, the nodes were still in a reboot process from `cvpUpdater`. This update makes `labModule.py` wait until all nodes are reachable.
Steps to test on a DC-Latest topo.
1. ssh to the jumphost and get into bash.
2. Run the following commands:
```
sudo echo "app: cvp-mlag" >> /etc/ACCESS_INFO.yaml
sudo sed -i 's/master/patch-labModule/g' /etc/repo.yaml
sudo reboot
```
After the jump host reboots, monitor the service scripts with 
`systemctl status atdFiles` and `systemctl status labModule`
As a note, `labModule` will …
> Patch lab module

- topologies/beta-routing/topo_build.yml
Increasing vEOS version to Lima.1 for further testing.
> Updating vEOS version on beta-routing topology

- topologies/beta-datacenter/topo_build.yml
- topologies/beta-routing/topo_build.yml
- topologies/datacenter-2019/Datacenter.yml
- topologies/datacenter-latest/Datacenter-nocvp.yml
- topologies/datacenter-latest/Datacenter.yml
- topologies/routing/Routing.yml
Updating the jumphost image to version 09-11. 
This image takes apt, pip and nodejs installs that were in `atdFiles` and are already installed in this jumphost version. This will reduce the overall execution time for atdFiles.
> updated jumphost images to 09-11

- labvm/services/cvpUpdater/cvpUpdater.py
- labvm/services/labModule/labModule.py
Setting the print functionality to false within the logging mechanism. This causes duplicate log messages in syslog for that script.
> Setting print of messages to false so only goes to syslog.

- topologies/all/labUI.py
Updates the links in the labUI page to reference the host path of the url instead of the current IP address of the instance.
> updated labUI to grab the hostname in the client request

- topologies/all/labUI.py
Updates the links in the labUI page to reference the host path of the url instead of the current IP address of the instance.
> [MASTER] brining labUI patch int master

- topologies/beta-datacenter/topo_build.yml
- topologies/beta-routing/topo_build.yml
- topologies/datacenter-2019/Datacenter.yml
- topologies/datacenter-latest/Datacenter-nocvp.yml
- topologies/datacenter-latest/Datacenter.yml
- topologies/routing/Routing.yml
Updated the jumphost version to the 2020-12-01 build. This build has UFW disabled, which caused some issues with dropping vxlan traffic in the ADC.
> updated jumphost images to 2020-12-01 version

- topologies/datacenter/labguides/source/eapi.rst
Updated script to leverage HTTPS instead of HTTP, since HTTP has been disabled from eAPI in the labs.
> updated eapi dc labguide to use https instead of http

- topologies/training-level1/topo_build.yml
- topologies/training-level2/topo_build.yml
- topologies/training-level3-2/topo_build.yml
- topologies/training-level3-exam/topo_build.yml
- topologies/training-level3/topo_build.yml
- topologies/training-level4/files/cvp/cvp_info.yaml
- topologies/training-level4/topo_build.yml
- topologies/training-level5/files/cvp/cvp_info.yaml
- topologies/training-level5/topo_build.yml
- topologies/training-level7/files/cvp/cvp_info.yaml
- topologies/training-level7/topo_build.yml
- Updated CVP CPU resources in training topologies
- Removed CVX from levels 4, 5 and 7
> Update to Training topos: (#536)

- nested-labvm/atd-docker/docker-compose.yml
- nested-labvm/atd-docker/gitConfigletSync/src/gitConfigletSync.py
app now waits 20 seconds instead of 10 to see if any pending tasks are generated"
> updated giconfigletsync build:

- topologies/datacenter/labguides/source/day2_operations.rst
- topologies/datacenter/labguides/source/rollback.rst
- topologies/dual-datacenter/labguides/source/day2_operations.rst
- topologies/dual-datacenter/labguides/source/rollback.rst
Minor updates to two programmability lab guides.  This guide can be pushed to both single and dual datacenter on any CVP version (lab doesnt use CVP).
- Corrected state on VLAN playbook from `replaced` to `overridden`
- This correctly removes all VLANs besides the one defined in group_vars
- Minor spelling and edits on wording
> Corrected playbook state settings and minor verbage in lab guide

- nested-labvm/atd-docker/docker-compose.yml
Reverting a portion of a change from #805. This adds back in the volume mount for the etc hosts file into the coder container.
> Readding the hosts file mount back into the coder container

- topologies/routing/labguides/source/ratd_mesh_guides/ratd_mesh_class_guides/c1_l3vpn_class_guide.rst
Minor typo in Class guide for EOS node name in L3VPN lab.
> Typo on EOS Node name for CE

- nested-labvm/atd-docker/coder/Dockerfile
Since we do not leverage a virtual environment on coder, we must set break system packages to true. Also setting pip flags to cleanup install commands. 
Also set coder version to latest at the time of this PR.
> Cleanup pip installs and allow breaking system packages

- .arista/secret_allowlist.yaml
The secret scanner has been updated to support `secret_literal` field in allow list. Use this instead since `secret_pattern` requires an regex pattern.
> Use `secret_literal` instead of `secret_pattern` in allow list
